package com.concordium.wallet.core.tracking

import android.content.Context

interface AppTracker {
    fun installation(context: Context)
    fun welcomeScreen()
    fun welcomeTermAndConditionsCheckBoxChecked()
    fun welcomeActivityTrackingCheckBoxChecked()
    fun welcomeGetStartedClicked()
    fun welcomeActivateAccountDialog()
    fun welcomeActivateAccountDialogCreateClicked()
    fun welcomeActivateAccountDialogImportClicked()
    fun welcomePasscodeScreen()
    fun welcomePasscodeEntered()
    fun welcomePasscodeConfirmationEntered()
    fun welcomePasscodeBiometricsDialog()
    fun welcomePasscodeBiometricsAccepted()
    fun welcomePasscodeBiometricsRejected()
    fun seedPhraseScreen()
    fun seedPhraseCopyClicked()
    fun seedPhraseCheckboxBoxChecked()
    fun seedPhraseContinueClicked()
    fun identityVerificationProvidersListScreen()
    fun identityVerificationScreen(provider: String)
    fun identityVerificationResultScreen()
    fun identityVerificationResultApprovedDialog()
    fun identityVerificationResultCreateAccountClicked()
    fun homeScreen()
    fun homeSaveSeedPhraseClicked()
    fun homeIdentityVerificationClicked()
    fun homeIdentityVerificationStateChanged(state: String)
    fun homeCreateAccountClicked()
    fun homeOnrampScreen()
    fun homeOnrampSiteClicked(siteName: String)
    fun homeOnrampBannerClicked()
    fun homeUnlockFeatureDialog()
    fun homeTotalBalanceClicked()
    fun aboutScreen()
    fun aboutScreenLinkClicked(url: String)
    fun homeNewsScreen()
}
