package com.concordium.wallet.core.tracking

import android.content.Context
import com.concordium.wallet.util.Log

class NoOpAppTracker : AppTracker {
    override fun installation(context: Context) = Log.d("No op")
    override fun welcomeScreen() = Log.d("No op")
    override fun welcomeTermAndConditionsCheckBoxChecked() = Log.d("No op")
    override fun welcomeActivityTrackingCheckBoxChecked() = Log.d("No op")
    override fun welcomeGetStartedClicked() = Log.d("No op")
    override fun welcomeActivateAccountDialog() = Log.d("No op")
    override fun welcomeActivateAccountDialogCreateClicked() = Log.d("No op")
    override fun welcomeActivateAccountDialogImportClicked() = Log.d("No op")
    override fun welcomePasscodeScreen() = Log.d("No op")
    override fun welcomePasscodeEntered() = Log.d("No op")
    override fun welcomePasscodeConfirmationEntered() = Log.d("No op")
    override fun welcomePasscodeBiometricsDialog() = Log.d("No op")
    override fun welcomePasscodeBiometricsAccepted() = Log.d("No op")
    override fun welcomePasscodeBiometricsRejected() = Log.d("No op")
    override fun seedPhraseScreen() = Log.d("No op")
    override fun seedPhraseCopyClicked() = Log.d("No op")
    override fun seedPhraseCheckboxBoxChecked() = Log.d("No op")
    override fun seedPhraseContinueClicked() = Log.d("No op")
    override fun identityVerificationProvidersListScreen() = Log.d("No op")
    override fun identityVerificationScreen(provider: String) = Log.d("No op")
    override fun identityVerificationResultScreen() = Log.d("No op")
    override fun identityVerificationResultApprovedDialog() = Log.d("No op")
    override fun identityVerificationResultCreateAccountClicked() = Log.d("No op")
    override fun homeScreen() = Log.d("No op")
    override fun homeSaveSeedPhraseClicked() = Log.d("No op")
    override fun homeIdentityVerificationClicked() = Log.d("No op")
    override fun homeIdentityVerificationStateChanged(state: String) = Log.d("No op")
    override fun homeCreateAccountClicked() = Log.d("No op")
    override fun homeOnrampScreen() = Log.d("No op")
    override fun homeOnrampBannerClicked() = Log.d("No op")
    override fun homeUnlockFeatureDialog() = Log.d("No op")
    override fun homeTotalBalanceClicked() = Log.d("No op")
    override fun homeOnrampSiteClicked(siteName: String) = Log.d("No op")
    override fun aboutScreen() = Log.d("No op")
    override fun aboutScreenLinkClicked(url: String) = Log.d("No op")
    override fun homeNewsScreen() = Log.d("No op")
}
