package com.concordium.wallet.core.tracking

import android.content.Context
import com.concordium.wallet.util.Log

class NoOpAppTracker : AppTracker {
    override fun installation(context: Context) = Log.d("No op")
    override fun welcomeScreen() = Log.d("No op")
    override fun welcomeTermAndConditionsCheckBoxChecked() = Log.d("No op")
    override fun welcomeActivityTrackingCheckBoxChecked() = Log.d("No op")
    override fun welcomeGetStartedClicked() = Log.d("No op")
    override fun welcomeSetUpWalletDialog() = Log.d("No op")
    override fun welcomeSetUpWalletDialogCreateClicked() = Log.d("No op")
    override fun welcomeSetUpWalletDialogImportClicked() = Log.d("No op")
    override fun passcodeScreen() = Log.d("No op")
    override fun passcodeSetupEntered() = Log.d("No op")
    override fun passcodeSetupConfirmationEntered() = Log.d("No op")
    override fun passcodeSetupBiometricsDialog() = Log.d("No op")
    override fun passcodeSetupBiometricsAccepted() = Log.d("No op")
    override fun passcodeBiometricsRejected() = Log.d("No op")
    override fun seedPhraseScreen() = Log.d("No op")
    override fun seedPhraseCopyClicked() = Log.d("No op")
    override fun seedPhraseCheckboxBoxChecked() = Log.d("No op")
    override fun seedPhraseContinueClicked() = Log.d("No op")
    override fun identityVerificationProvidersListScreen() = Log.d("No op")
    override fun identityVerificationScreen(provider: String) = Log.d("No op")
    override fun identityVerificationResultScreen() = Log.d("No op")
    override fun identityVerificationResultApprovedDialog() = Log.d("No op")
    override fun identityVerificationResultCreateAccountClicked() = Log.d("No op")
    override fun homeScreen() = Log.d("No op")
    override fun homeSaveSeedPhraseClicked() = Log.d("No op")
    override fun homeIdentityVerificationClicked() = Log.d("No op")
    override fun homeIdentityVerificationStateChanged(state: String) = Log.d("No op")
    override fun homeCreateAccountClicked() = Log.d("No op")
    override fun homeOnrampScreen() = Log.d("No op")
    override fun homeOnrampBannerClicked() = Log.d("No op")
    override fun homeUnlockFeatureDialog() = Log.d("No op")
    override fun homeTotalBalanceClicked() = Log.d("No op")
    override fun homeOnrampSiteClicked(siteName: String) = Log.d("No op")
    override fun aboutScreen() = Log.d("No op")
    override fun aboutScreenLinkClicked(url: String) = Log.d("No op")
    override fun discoverScreen() = Log.d("No op")
    override fun reviewAppDialog() = Log.d("No op")
    override fun reviewAppDialogCancelClicked() = Log.d("No op")
    override fun reviewAppDialogSubmitClicked() = Log.d("No op")
}
