name: Build release packages for Google Play publishing

on:
  push:
    # Run only for releases: ignore versions with meta part (1.2.3-qa.1, 3.4.5-rc.2, etc).
    tags:
      - "*.*.*"
      - "!*-*"
  workflow_dispatch:

env:
  java_version: "11"

jobs:
  build:
    runs-on: ubuntu-latest

    environment:
      name: Google Play
      url: https://play.google.com/store/apps/details?id=com.pioneeringtechventures.wallet

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "${{env.java_version}}"
          distribution: corretto
          cache: gradle

      - name: Check if build version matches the tag
        run: |
          buildVersion="$(./gradlew -q printVersionName)"
          tagVersion="${GITHUB_REF#refs/tags/}"
          if [ "$buildVersion" != "$tagVersion" ]; then
            echo "Build version '$buildVersion' doesn't match the tag '$tagVersion'"
            exit 1
          fi
        shell: bash
        env:
          SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}

      - name: Build Testnet APK and bundle
        run: ./gradlew app:assembleTstnetRelease app:bundleTstnetRelease --stacktrace

      - name: Build Mainnet APK and bundle
        run: ./gradlew app:assembleMainnetRelease app:bundleMainnetRelease --stacktrace

      - name: Upload the APKs and bundles
        uses: actions/upload-artifact@v3
        with:
          name: APKs and bundles
          path: |
            app/build/outputs/**/*.apk
            app/build/outputs/**/*.aab
          compression-level: 0
